Lesson 5
IVFromBy/WebStore pull request #5
Opened 2021-02-01 21:13 UTC by IVFromBy

подключение к БД
первая миграция данных
Редактор данных в бд

2021-02-07 12:55 UTC, Infarh requested changes
Убрать повторяющийся код проекций данных
Убрать запросы `SET IDENTITY_INSERT ... ON/OFF`
Добавить в сущности свойство IsDeleted и модифицировать методы запросов так, чтобы они учитывали этот флаг и возвращали данные только с невыставленным флагом.

2021-02-07 21:23 UTC, IVFromBy commented
Не понял зачем убирать запросы `SET IDENTITY_INSERT ... ON/OFF`. Во время миграции будет ругаться

2021-02-08 18:11 UTC, Infarh commented
Напрямую лезть в базу такими запросами признак недоработок в архитектуре приложения. Миграция от этого пострадать не должна потому что мы не меняем структуры БД. Нужно лишь переосмыслить способ формирования набора тестовых данных.

2021-02-08 20:00 UTC, IVFromBy commented
На ум пришёл такой подход, подставить случайный бренд и секцию для тестового продукта.

2021-02-10 15:55 UTC, IVFromBy commented
Очень интересный подход. Но я не до конца понимаю, как EF создала связи. 
Есть 5 этапа: 
 1) создали объект который хранит связь продуктов с категориями
 2) создали объект который хранит связь продуктов с брендами
 3) создали объект который хранит связь между родительской и дочерней категорией товаров
 4) убрали связь в продуктах и категориях
 5) Отправляем на сервер коллекции, у которых сброшены связи 

Итого, на сервер мы отправили объекты, которые не хранят связь. Как EF поняла как нужно сделать связь, если мы сказали сохранить объекты лишённые связи...

2021-02-14 10:25 UTC, merged